config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :all_tasks, only: [:index, :create, :update, :destroy]

  # GET /tasks
  # GET /tasks.json


  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.create(task_params)

    
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task.update(task_params)
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def all_tasks
      @tasks = Task.all
    end
    
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <div class="container">
    <%= yield %>
    
    </div>
    
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.text_field :deadline, id: "datetimepicker1", placeholder: "when is it due?" %>
    
    </div>
    
    
  <div class="form-group">
    <%= f.button :Submit, class: "btn btn-primary" %>
  </div>
  
  <% end %>

app/views/tasks/_task.html.erb
<div class="col-md-12">
    <div class="well">

    <h3><%= link_to task.description, task, remote: true, method: :delete, data: {confirm: 'are you sure?' } %></h3>
    <p><%= task.deadline %></p>
    
    <p class="pull-right">
    
    
    <%= link_to "edit", edit_task_path(task), remote: true %>
    
    </p>
    </div>
</div>

app/views/tasks/create.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(1350);

app/views/tasks/destroy.js.erb
$('#tasks').html("<%= j (render @tasks) %>");

app/views/tasks/edit.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-5">
      <%= link_to new_task_path, remote: true do %>

           <button class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Add Task </button>
      <% end %>


        <div id="task-form" style="display:none;"></div>
        
      </div>

      <div class="col-md-8">

            <h2> tasks</h2>
            
              <div id="tasks">
                
                <div class="row">
                <%= render @tasks %>
                </div>
                
              </div>
            

        </div>

</div>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(1350);